hmcts/pcq-shared-infrastructure

prod.tfvars

https://tools.hmcts.net/jira/browse/PCQ-328
Updated to add managed identity objectid for production.
```
[ ] Yes
[x] No
```

PCQ-328 Adding managed identity for production.

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-678
Update to delete blobs after 90 days.
```
[ ] Yes
[x] No
```

PCQ-678 Adding expiration rule.

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-678
Add missing blobtype to new expiration rule.
```
[ ] Yes
[x] No
```

PCQ-678 Add missing blobtype.

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-678
Update to storage account rules to delay archive until blob is deleted.
```
[ ] Yes
[x] No
```

PCQ-678 Update storage account rules

---

aat.tfvars
demo.tfvars
ithc.tfvars
key-vault.tf
perftest.tfvars
prod.tfvars

https://tools.hmcts.net/jira/browse/PCQ-651
Remove old MI
```
[ ] Yes
[x] No
```

PCQ-651: Remove old MI

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-1002
Update to vnet rules for rebuilt AAT environment.
```
[ ] Yes
[x] No
```

PCQ-1002: Updated vnet rules.

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/PCQ-988
This change is about syncing other infrastructure branches with master
```
[ ] Yes
[x] No
```

Sync Infrastructure Branches with Master

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-1118
This change is to update preview cluster
```
[ ] Yes
[x] No
```

PCQ-1118 Update Preview

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-1118
Update preview vnet configuration
```
[ ] Yes
[x] No
```

PCQ-1118: Update preview vnet configuration

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-1105
This change is to change Storage account replication setting from LRS to ZRS
```
[ ] Yes
[x] No
```

PCQ-1105 replication settings change

---

storage-account.tf

https://tools.hmcts.net/jira/browse/DTSPO-5564
Adds new cft-prod vnet and rg

Adds new cft-prod vnet and rg

---

storage-account.tf

Reverts hmcts/pcq-shared-infrastructure#20

Revert "Adds new cft-prod vnet and rg"

---

storage-account.tf

https://tools.hmcts.net/jira/browse/PCQ-1243
Blob Storage access fix.
```
[ ] Yes
[x] No
```

PCQ-1243: Fix access to blob storage

---

providers.tf
storage-account.tf

Adds logic to whitelist both cft-prod and core-prod networks
```
[ ] Yes
[ ] No
```

Adds logic to whitelist both cft-prod and core-prod networks

---

application-insights.tf
state.tf

https://tools.hmcts.net/jira/browse/PCQ-969
Upgrade terraform azurerm provider to 3.3.0.
```
[ ] Yes
[x] No
```

PCQ-969: Update to upgrade azurem provider.

---

storage-account.tf

Fix demo access to storage-account.
```
[ ] Yes
[x] No
```

PCQ: Fix storage-account demo access,

---

README.md

https://tools.hmcts.net/jira/browse/PCQ-1593
Add License badge and Overview section
```
[ ] Yes
[x] No
```

PCQ-1593 Add License badge and Overview section

---

storage-account.tf

Remove aks-infra as this resource no longer exitsts
```
[ ] Yes
[x] No
```

Remove aks-infra (no longer exists)

---

app-insights.tf
state.tf
storage-account.tf
variables.tf

Add appinsights secret
```
[ ] Yes
[x] No
```

Add appinsights secret

---

alerts.tf
variables.tf

To create an alert for consolidation service if it did not run successfully
```
[ ] Yes
[x] No
```

PCQ-1785 creating alert for consolidation

---

aat.tfvars
alerts.tf

Changing to existing resource group instead of creating one
```
[ ] Yes
[x] No
```

PCQ-1785 changing to existing resource group

---

alerts.tf
application-insights.tf

Changing app insight location from west Europe to UK south
```
[ ] Yes
[x] No
```

PCQ-1785 changing location from west Europe to UK South

---

alerts.tf
application-insights.tf

Changing to string
```
[ ] Yes
[x] No
```

PCQ-1785 changing string

---

alerts.tf

Changing alert location to westeurope
```
[ ] Yes
[x] No
```

PCQ-1785 creating alerts in westeurope

---

alerts.tf

Only checking for error in prod
```
[ ] Yes
[x] No
```

PCQ-1785 only check for error in consolidation

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/PCQ-1806
Config renovate
```
[ ] Yes
[x] No
```

PCQ-1806 config renovate

---

aat.tfvars
alerts.tf
demo.tfvars
ithc.tfvars
key-vault.tf
main.tf
perftest.tfvars
prod.tfvars
storage-account.tf
variables.tf

https://tools.hmcts.net/jira/browse/LAU-915
Adding alert for disposer on aat  if there is an error

Lau 915 Creating disposer alert on aat

---

alerts.tf

https://tools.hmcts.net/jira/browse/LAU-915
Changing short name and remove email

LAU-915 changing short name

---

alerts.tf

https://tools.hmcts.net/jira/browse/LAU-915
Alert query

LAU-915 alerts query

---

alerts.tf
demo.tfvars
prod.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/LAU-915
Enabling alerts on prod

LAU-915 enabling on prod

---

alerts.tf
demo.tfvars

https://tools.hmcts.net/jira/browse/LAU-913
Creating a summary alert for PCQ Consolidation service which will be pushed in slack channel
Testing on demo

PCQ-1963 consolidation summary alert

---

demo.tfvars

https://tools.hmcts.net/jira/browse/PCQ-1963
Consolidation summary alert

PCQ-1963 disposer_time_window_in_minutes

---

alerts.tf
demo.tfvars
key-vault.tf
prod.tfvars

https://tools.hmcts.net/jira/browse/PCQ-1963
Enable summary alert on prod and push alert monitoring email in secret
Testing completed on demo

PCQ-1963 enable summary on prod and push alert failure email to secret

---

demo.tfvars

https://tools.hmcts.net/jira/browse/PCQ-1963
disable summary on demo 
Testing done on demo

PCQ-1963 disbale summary alerts on demo

---

alerts.tf
demo.tfvars
variables.tf

https://tools.hmcts.net/jira/browse/PCQ-1964
Create an alert for PCQ Loader failure and enable on demo

PCQ-1964 adding alerts for pcq loader failure

---

demo.tfvars
prod.tfvars

https://tools.hmcts.net/jira/browse/PCQ-1964
Enable alert on production
Testing completed on demo

PCQ-1964enable PCQ Loader alert on production

---

variables.tf

Frequency to go back again 24 hours so that we get alert everyday at 7

Frequency back again 24 hours

---

alerts.tf
variables.tf

frequency change in PCQ to give summary alert and early alert for failure
Testing is completed

Change in frequency to 1140 and early alert failure

---

variables.tf

https://tools.hmcts.net/jira/browse/LAU-947
Alert time tweak
will be checked by summary alerts

LAU-947 summary alert time change

---

variables.tf

https://tools.hmcts.net/jira/browse/LAU-947
Frequency to 1440 mins
slack alerts testing

LAU-947 frequency back to 1440

---

alerts.tf
variables.tf

https://tools.hmcts.net/jira/browse/LAU-947
Adding alert back

Adding alert back

---

alerts.tf

https://tools.hmcts.net/jira/browse/PCQ-2038
Change the message to look for Summary alert
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

PCQ-2038summary alert message change

---

alerts.tf

https://tools.hmcts.net/jira/browse/PCQ-2038
slight change in summary alert
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

slight change in message
